#!/usr/bin/env node

/**
 * Usage:
 * 
 *     $ duplicate path newFileName
 *
 * Duplicates the file at `path` as `newFileName` in the same directory.
 * Alternative to `cp path path` which can get verbose if you're not already
 * in the target path. For example:
 *
 *     $ cp path/to/some/file/name.ext path/to/some/file/newname.ext
 *     $ duplicate path/to/some/file/name.ext newname.ext
 *
 * TODO:
 *
 * - Support directory duplication
 * - Optional newFileName: auto-increment " copy N" to the end of the file
 *     before extension, just as OSX does
 * - CLI help: `duplicate -h` or simply `duplicate` with no arguments
**/

var fs = require('fs');
var path = require('path');

// Simple alias methods for stderr and exit:
var stderr = function(msg) { process.stderr.write(msg + '\n'); };
var exit = process.exit.bind(process);

// Grab the arguments
var filePath = process.argv[2];
var newName = process.argv[3];

// Check for a file name given to duplicate:
if (!filePath) {
  stderr('duplicate: file path not given');
  exit(1);
}

// Make sure the given file exists:
var exists = fs.existsSync(filePath);
var isFile = exists && fs.statSync(filePath).isFile();

if (!isFile) {
  stderr('duplicate: \'' + filePath + '\' is not a file')
  exit(1);
}

// Check for a new name for the file:
if ((newName || '').trim() == '') {
  stderr('duplicate: new file name not given');
  exit(1);
}

var absolute = path.resolve(filePath);
var directory = path.dirname(absolute);
var newPath;

if (newName.match(/^~|\//)) {
  // Use literal path if new name is absolute:
  newPath = newName;
} else {
  // Join to previous directory if relative:
  newPath = path.join(directory, newName);
}

// Make sure something doesn't already exist at that path:
if (fs.existsSync(newPath)) {
  stderr('duplicate: a file already exists at \'' + filePath + '\'');
  exit(1);
}

// Copy existing file to new path:
fs.createReadStream(filePath).pipe(fs.createWriteStream(newPath));
